const CATS=['Pacientes','Escalas','Profissionais','Documentação','Financeiro','Convênios','Contratos','Atendimento às famílias','Recursos Humanos','Administrativo'];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s), pad=n=>String(n).padStart(2,'0');
const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const fmt=d=>d.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let tasks=[],user=null,view='today',cursor=new Date(),channel=null;
const cfg=window.APP_CONFIG||{};
const db=window.supabase.createClient(cfg.SUPABASE_URL||'',cfg.SUPABASE_PUBLISHABLE_KEY||'');
const sync=t=>$('#syncState').textContent=t;
const fromDb=t=>({id:t.id,ownerUserId:t.user_id,accessLevel:t.access_level||'private',title:t.titulo,date:t.data,time:t.hora?t.hora.slice(0,5):'',category:t.categoria||'',priority:t.prioridade||'medium',status:t.status||'Pendente',owner:t.responsavel||'',patient:t.paciente||'',professional:t.profissional||'',phone:t.telefone||'',notes:t.observacoes||''});
const toDb=t=>({user_id:t.ownerUserId||user.id,access_level:t.accessLevel||'private',titulo:t.title,data:t.date,hora:t.time||null,categoria:t.category,prioridade:t.priority,status:t.status,responsavel:t.owner||null,paciente:t.patient||null,profissional:t.professional||null,telefone:t.phone||null,observacoes:t.notes||null,updated_at:new Date().toISOString()});
function filters(){const q=$('#searchInput').value.toLowerCase(),c=$('#categoryFilter').value,s=$('#statusFilter').value,p=$('#priorityFilter').value;return tasks.filter(t=>(!q||[t.title,t.patient,t.professional,t.owner,t.notes].join(' ').toLowerCase().includes(q))&&(!c||t.category===c)&&(!s||t.status===s)&&(!p||t.priority===p));}
async function load(){if(!user)return;sync('Sincronizando...');const {data,error}=await db.from('tasks').select('*').order('data').order('hora');if(error){sync('Erro');alert(error.message);return}tasks=(data||[]).map(fromDb);sync('Sincronizado');render();}
async function persist(t){sync('Salvando...');let q=t.id?db.from('tasks').update(toDb(t)).eq('id',t.id).select().single():db.from('tasks').insert(toDb(t)).select().single();const {data,error}=await q;if(error)throw error;sync('Sincronizado');return fromDb(data)}
function realtime(){if(channel)db.removeChannel(channel);channel=db.channel('tasks-'+user.id).on('postgres_changes',{event:'*',schema:'public',table:'tasks'},load).subscribe();}
function stats(){const today=key(new Date());$('#pendingCount').textContent=tasks.filter(t=>t.status==='Pendente').length;$('#progressCount').textContent=tasks.filter(t=>t.status==='Em andamento').length;$('#waitingCount').textContent=tasks.filter(t=>t.status==='Aguardando retorno').length;$('#lateCount').textContent=tasks.filter(t=>t.date<today&&!['Concluída','Cancelada'].includes(t.status)).length;}
function isOwner(t){return t.ownerUserId===user?.id}
function canEdit(t){return isOwner(t)||t.accessLevel==='edit'}
function accessLabel(t){
  if(isOwner(t)) return t.accessLevel==='private'?'Minha · Privada':t.accessLevel==='view'?'Minha · Compartilhada para leitura':'Minha · Compartilhada para edição';
  return t.accessLevel==='edit'?'Compartilhada · Pode editar':'Compartilhada · Somente leitura';
}
function taskHtml(t){const done=t.status==='Concluída',info=[t.time&&`🕒 ${t.time}`,t.category&&`📁 ${t.category}`,t.patient&&`👤 ${t.patient}`,t.professional&&`🩺 ${t.professional}`,`🔐 ${accessLabel(t)}`,`• ${t.status}`].filter(Boolean).join(' ');return `<div class="task ${t.priority} ${done?'done':''}"><input type="checkbox" ${done?'checked':''} ${canEdit(t)?'':'disabled'} onchange="toggleTask('${t.id}')"><div><div class="task-title">${esc(t.title)}</div><div class="task-meta">${esc(info)}</div>${t.notes?`<div style="margin-top:8px;font-size:13px">${esc(t.notes)}</div>`:''}</div><button class="icon-btn" onclick="editTask('${t.id}')">${canEdit(t)?'✎':'👁'}</button></div>`}
function sow(d){const x=new Date(d),day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));x.setHours(0,0,0,0);return x}
function render(){stats();const ft=filters(),k=key(cursor),day=ft.filter(t=>t.date===k).sort((a,b)=>(a.time||'99').localeCompare(b.time||'99'));$('#todayDateLabel').textContent=fmt(cursor);$('#todayTasks').innerHTML=day.length?day.map(taskHtml).join(''):'<div class="empty">Nenhuma tarefa para este dia.</div>';const done=day.filter(t=>t.status==='Concluída').length,pct=day.length?Math.round(done/day.length*100):0;$('#dailyProgress').style.width=pct+'%';$('#dailyProgressText').textContent=`${done} de ${day.length} tarefa(s) concluída(s)`;
const st=sow(cursor),names=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'];$('#weekGrid').innerHTML=names.map((n,i)=>{const d=new Date(st);d.setDate(st.getDate()+i);const list=ft.filter(t=>t.date===key(d));return `<div class="day-col ${key(d)===key(new Date())?'today':''}"><div class="day-head">${n}<small>${d.toLocaleDateString('pt-BR')}</small></div>${list.length?list.map(t=>`<div class="mini-task ${t.priority}" onclick="editTask('${t.id}')"><strong>${esc(t.title)}</strong><br>${t.time||'Sem horário'} · ${esc(t.category)}</div>`).join(''):'<div class="empty" style="padding:18px 6px">Sem tarefas</div>'}</div>`}).join('');
const y=cursor.getFullYear(),m=cursor.getMonth(),first=sow(new Date(y,m,1));let cells='';for(let i=0;i<42;i++){const d=new Date(first);d.setDate(first.getDate()+i);const list=ft.filter(t=>t.date===key(d));cells+=`<div class="month-day ${d.getMonth()!==m?'muted':''} ${key(d)===key(new Date())?'today':''}"><div class="month-number">${d.getDate()}</div>${list.slice(0,3).map(t=>`<div class="month-item" onclick="editTask('${t.id}')">${esc(t.title)}</div>`).join('')}${list.length>3?'<small>+ mais</small>':''}</div>`}$('#monthGrid').innerHTML=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(x=>`<div class="month-head">${x}</div>`).join('')+cells;
const labels={today:['Visão de hoje',fmt(cursor)],week:['Visão semanal',st.toLocaleDateString('pt-BR')],month:['Visão mensal',cursor.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})]};$('#pageTitle').textContent=labels[view][0];$('#pageSubtitle').textContent=labels[view][1];}
function setView(v){view=v;$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));render()}
function modal(t=null){
  const editable=!t||canEdit(t), owner=!t||isOwner(t);
  $('#taskModal').classList.add('open');
  $('#modalTitle').textContent=t?(editable?'Editar tarefa':'Visualizar tarefa'):'Nova tarefa';
  $('#deleteBtn').style.display=t&&owner?'inline-block':'none';
  [['taskId',t?.id||''],['title',t?.title||''],['date',t?.date||key(cursor)],['time',t?.time||''],['category',t?.category||CATS[0]],['priority',t?.priority||'medium'],['status',t?.status||'Pendente'],['owner',t?.owner||''],['patient',t?.patient||''],['professional',t?.professional||''],['phone',t?.phone||''],['notes',t?.notes||''],['accessLevel',t?.accessLevel||'private']].forEach(([id,v])=>$('#'+id).value=v);
  ['title','date','time','category','priority','status','owner','patient','professional','phone','notes'].forEach(id=>$('#'+id).disabled=!editable);
  $('#accessLevel').disabled=!owner;
  $('#saveTaskBtn').style.display=editable?'inline-block':'none';
}
function closeModal(){$('#taskModal').classList.remove('open')}
window.editTask=id=>modal(tasks.find(t=>t.id===id));window.toggleTask=async id=>{const t=tasks.find(x=>x.id===id);if(!t||!canEdit(t))return;const old=t.status;t.status=old==='Concluída'?'Pendente':'Concluída';render();try{await persist(t)}catch(e){t.status=old;render();alert(e.message)}};
$('#taskForm').onsubmit=async e=>{e.preventDefault();const existing=tasks.find(x=>x.id===$('#taskId').value);const t={id:$('#taskId').value||null,ownerUserId:existing?.ownerUserId||user.id,accessLevel:$('#accessLevel').value,title:$('#title').value.trim(),date:$('#date').value,time:$('#time').value,category:$('#category').value,priority:$('#priority').value,status:$('#status').value,owner:$('#owner').value.trim(),patient:$('#patient').value.trim(),professional:$('#professional').value.trim(),phone:$('#phone').value.trim(),notes:$('#notes').value.trim()};try{const saved=await persist(t),i=tasks.findIndex(x=>x.id===saved.id);i>=0?tasks[i]=saved:tasks.push(saved);closeModal();render()}catch(err){alert(err.message)}};
$('#deleteBtn').onclick=async()=>{const id=$('#taskId').value,t=tasks.find(x=>x.id===id);if(id&&t&&isOwner(t)&&confirm('Excluir esta tarefa?')){const {error}=await db.from('tasks').delete().eq('id',id);if(error)return alert(error.message);tasks=tasks.filter(t=>t.id!==id);closeModal();render()}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#authMessage').textContent='Entrando...';const {error}=await db.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});$('#authMessage').textContent=error?error.message:''};$('#logoutBtn').onclick=()=>db.auth.signOut();
async function session(s){user=s?.user||null;if(user){$('#authScreen').style.display='none';$('#appRoot').style.display='grid';await load();realtime()}else{$('#appRoot').style.display='none';$('#authScreen').style.display='grid'}}db.auth.onAuthStateChange((_,s)=>session(s));db.auth.getSession().then(({data})=>session(data.session));
$('#category').innerHTML=CATS.map(c=>`<option>${c}</option>`).join('');$('#categoryFilter').innerHTML='<option value="">Todas as categorias</option>'+CATS.map(c=>`<option>${c}</option>`).join('');$$('.nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));['searchInput','categoryFilter','statusFilter','priorityFilter'].forEach(id=>$('#'+id).oninput=render);$('#newTaskBtn').onclick=()=>modal();$('#closeModal').onclick=$('#cancelBtn').onclick=closeModal;$('#printBtn').onclick=()=>print();$('#todayBtn').onclick=()=>{cursor=new Date();render()};$('#prevBtn').onclick=()=>{view==='today'?cursor.setDate(cursor.getDate()-1):view==='week'?cursor.setDate(cursor.getDate()-7):cursor.setMonth(cursor.getMonth()-1);render()};$('#nextBtn').onclick=()=>{view==='today'?cursor.setDate(cursor.getDate()+1):view==='week'?cursor.setDate(cursor.getDate()+7):cursor.setMonth(cursor.getMonth()+1);render()};$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('homecareTheme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('homecareTheme')==='dark')document.body.classList.add('dark');render();
